### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#12]
The forum is being unreasonably slow, and more often than not just doesn't load.
I would label this 'Bug'

Speed it up pl0x? Lawl.
I would label this 'Idea'

I know you can't do that if it's something Jamoola, or whatever you use, based. >.<

**Comment by Deceth** [comment]
Closing this because nothing anyone could ever do to the Battle City source code would ever speed up the website =p 

Looble is on cheap web-hosting. Good price, not always reliable. I'd love to get something faster, but I'm already loosing money hosting a server...

**Comment by Rushing** [comment]
Tomorrow you should be getting £10, if I remember to stick it on my unbelievably empty card. D:
