### ISSUE TITLE
Crash bug.

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#13]
When a player clicks Exit, sometimes after they click okay it crashes.

Information on the bug:
It seems to only happen when the game is in fullscreen mode, I've never seen it happen in windowed.
It also only seems to happen if you press OK <u>quickly</u> Pressing exit, waiting 5 seconds, pressing OK and you don't crash. Atleast, not as often.
The more players that are on, the more it crashes.

**Comment by rileyw** [comment]
@Deceth Proposing that this issue be closed considering that we cannot reproduce at this time. May be reopened if more information can be provided at a future date.

**Comment by Deceth** [comment]
Good idea, done!
