### ISSUE TITLE
Secondary Advantages

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#16]
Currently, only two buildings have secondary advantages;
The Med-Kit factory allows the hospital to be built.
The Orb Factory allows you to be orbed.

I think that most if not all buildings should have these abilities, I have already suggested one;
Cloak Factory allows the Decoy House to be built. I will post a few more now.

**Comment by Rushing** [comment]
Posted 'a few more'.
The main idea behind these is to diversify the buildings, but without needing people to redesign all their old cities to do so.

**Comment by Deceth** [comment]
Lots of buildings allow other things to be built, hence the concept of research. That doesn't mean other buildings cannot be added, just saying that virtually all buildings have a secondary advantage except those at the end branch of the building tree.

Also, bomb factory also allows you to be orbed!

**Comment by Rushing** [comment]
I never knew Bomb Factory made you orbable!
That aside, by Advantages I mean unique factors. Researches have factories, sure, but only Med-Kits actually have something unique that is unlocked.

**Comment by Deceth** [comment]
Researches also unlock other types of research, not just factories.

**Comment by Rushing** [comment]
Now you're just being Picky hehe. You know exactly what I mean.

**Comment by Deceth** [comment]
When gathering requirements, you must be picky and drill down the the smallest detail. Otherwise you'll end up with a goat when you ordered a cow.

**Comment by Rushing** [comment]
I suppose that makes sense, but the requirement is fairly simple. I think we would all enjoy a few new elements in the game, which don't require older players to adapt what they already know, and aren't just more of the old stuff.

**Comment by Deceth** [comment]
Closing this. It has been expanded into several individual topics. Thanks!
