### ISSUE TITLE
Slow Zone

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#17]
Wall factory allows you to build a 'Slow Zone', again a 3x3 non-dense building, that when stepped on reduces speed by 50%. Needs no population, but can be bombed. Interesting idea; what if bullets travelled slowly along it too, and bombs took longer to blow? DFG's held you for longer too!

**Comment by Deceth** [comment]
Closing this thread, feel free to bring it back for future discussion but I don't feel we're going to be heading down this route and it hasn't gained any traction in the last three years.
