### ISSUE TITLE
Damage Pad

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#18]
Bazooka Factory allows you to build a 'Damage pad', a 3x3 non-dense building, that when stepped on gives 10% damage to whoever stepped on it, friend or foe. Needs to be populated, and can be bombed like normal.

**Comment by Deceth** [comment]
Like a giant mine?

**Comment by Rushing** [comment]
Like a giant, non-biast mine. Yes.

**Comment by Deceth** [comment]
Closing this, idea hasn't gained any traction. Not sure it fits with the current game-play as described above, maybe as an item, but, sounds like a bigger mine.
