### ISSUE TITLE
Nowhere else I can put this really, Designer Lost!

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#21]
Deceth, do you have a copy of the Battle City Designer tool by Hanzie on your PC? If not, I fear it may be lost forever... The download link is dead.
If you do, could you upload it for us please?

**Comment by Deceth** [comment]
Closing this issue because nothing anybody could ever do to the Battle City source code would ever solve this issue. Ask someone on the forums for the file, surely someone has it.

**Comment by Rushing** [comment]
I've asked on the forum, and nobody replied with good news, and you didn't reply at all. Therefor I took the logical route of contacting you, and posted it on here. :)
