### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#22]
client\cgame.cpp(415) : error C2039: 'RequestAutoBuild' : is not a member of 'CProcess'
client\cgame.cpp(420) : error C2039: 'RequestSaveCity' : is not a member of 'CProcess'

client\cingame.cpp(252) : error C2653: 'CUtil' : is not a class or namespace name
client\cingame.cpp(252) : error C3861: 'getLineSplitOnSpace': identifier not found
client\cingame.cpp(336) : error C2653: 'CUtil' : is not a class or namespace name
client\cingame.cpp(336) : error C3861: 'getLineSplitOnSpace': identifier not found

client\cprocess.cpp(1944) : error C2039: 'splitStringIntoInts' : is not a member of 'CInGame'

1>BattleCity - 7 error(s), 12 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

If anyone can give any hints towards the source of any of these, it would be much appriciated

**Comment by Deceth** [comment]
http://forums.nvidia.com/lofiversion/index.php?t73367.html

**Comment by Deceth** [comment]
Ahh, the current version of Battle City is 3.5.7. CUtil is introduced in version 3.5.8 in this commit: http://github.com/Deceth/Battle-City/commit/7989d8f88610696febb088f91c609f660bdbe342

So, at this point, we can find a working Cutil.h, or, roll-back the source back to 3.5.7 so it compiles.

**Comment by Rushing** [comment]
Since the additions in 3.5.8 are fairly trivial and not really important, it's not a bad idea to roll back.

**Comment by Deceth** [comment]
I've branched 3.5.8 into a new branch named "better-chat". The master repository now contains the source code for 3.5.7 which will compile.
