### ISSUE TITLE
Grenade?!

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#24]
A simple item that can fly over four tiles (Including dense tiles, i.e buildings ;) ) and will then 'detonate' sending a ring of laser shots flying out.
Useful for:
- Attacking mayors who just sit and rebuild non stop instead of defending
- Hitting some of those impossible to get turrets with more ease (Don't need to do the really hard hook shot move)
- Defending from a far safer position (Within the city!)
- Clearing mines and dfgs

Useful for newbies who can hide and live alot longer before needing to face to face confront enemies
Number of item: 3
Building Tree: Comes right after Cougars are done

**Comment by Deceth** [comment]
Grenade could be an interesting weapon, as long as you can't shoot too many.

**Comment by Rushing** [comment]
Hence why you are only given 3 per city: :)

**Comment by Deceth** [comment]
I think we need to put this idea aside for now, while we focus on higher priority issues. This could come back again in the future if we get to the point where we start discussing the sorts of options that can be configured on servers. 

(i.e - we will want players to be able to create servers with unique configurations and possibly a unique set of items so an unlimited amount of different gameplay experience can become a possibility... but we're not there yet.)
