### ISSUE TITLE
Wiki page issue

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#25]
Whenever I create a new wiki page, it shows up as grey on the main page (Even after I actually add the page). It's still clickable and shows the correct page in the side bar list of links.
The fix is to create a new page, and then delete that page again after updating. I don't know why it does this, but it's annoying. I'm really placing this in the wrong place, should be posted on the Github support thread. Why am I still talking? Look! A spoon! _Wanders off rambling_

**Comment by Deceth** [comment]
I'm not sure how to respond to this. I am less baffled by a Rubik's cube.

**Comment by Rushing** [comment]
That's what she said =)

**Comment by Rushing** [comment]
Rushing  about 23 hours ago  | link  | edit  | delete

That's what she said =)

23 hours ago? I litterally JUST posted that. Lmao. Silly Wiki.

**Comment by Deceth** [comment]
Doesn't happen to me. Like you said, ask Github =p
