### ISSUE TITLE
Flash/Browser?

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#26]
I have next to no information about Flash, Java or PHP. But how hard/would one go about/easy would be to create a browser based version of BattleCity?

**Comment by Deceth** [comment]
How hard would it be? That's a pretty relative question... How well do you know the language in question, how good are you at programming, how much time do you have, how many games have you created in the passed, how big is your development team, how big is your budget?

**Comment by Rushing** [comment]
Well, to summerize a lot of those questions into one answer: Not alot.
I just remember seeing on the forums that it was possible to already load it in a browser if you openened it in a java SDK. I don't remember the forum or the correct term, but if it were as easy as that, then why not? =p

**Comment by Deceth** [comment]
There is no magic button that I am familiar with that will turn a C++ application into something that will run in a browser.

**Comment by Rushing** [comment]
You're meant to be the evil overlord, what a devilishly masterfull application this would be!

**Comment by rileyw** [comment]
Unity3D provides a mechanism for publishing a game to multiplatforms which includes browsers capable of installing the Unity Web Player. Developing Battle City to be playable via the browser will increase its accessibility which we could hope leads to increased active player numbers.
- Publish browser game to networks such as kongregate.com
- Model Battle City to be similar to Realm of the Mad God.
