### ISSUE TITLE
A few old changes to be undone.

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#3]
I feel that a few of the older changed need to be undone for this game. I remember when mines did around 50% damage, that was a lot more fun than what they currently did.
Newbies seem to like mines, they are one of the easier weapons in the game to use, and currently, with 5 meds, a player can easily tank over mines. This is the first change I would wish to be undone, put the mines damage back up to around 50%

The second, I have already mentioned. We now have 5 med kits, I know this is so to make it more newbie friendly again, but I severely dislike it. Currently we have few people on, so we often have the issue of 1v1's, meaning the newbie takes 3 meds, and the pro takes 5 meds. He just tanks the whole battle, making it unfair for the newbie.

The third, 5 dfgs. Again, why? DFG's are the counterpart to Mines. When they were both lowered, it was even, then dfgs got 5, and it was already unfair for the attacker. Then you added flares. This is HORRIBLY unfair on defenders. 4 dfg's is much fairer, and 50% damage mines is 100% fair.

The last change, rotating cities. I think this one is an important one. Twice I heard this, or something akin to this being said;
'Durr, I have no cities saved for any of these'
This I have now realized, is a rather large problem. New players, generally join more than once at least. When they rejoin, they see new cities and thus need to start over again. I hope you put it back to the Normal starting cities, and have them increase as more players get on.

**Comment by Deceth** [comment]
Thanks for the ideas. I split this up into 4 separate ideas so it will be easier to discuss. For example, if people vote this idea up or down, which ideas are they referring too? It will be easier to follow the discussion having them separate and know which is most important to the community.
