### ISSUE TITLE
I have nowhere else to put this =/    Wiki Development page

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#33]
Would you people mind starting to use the Wiki Development Page that I created? It's very frustrating to need to check EVERY last page for even the smallest update. I would must rather just check the WDP, see Deceth: Added, I'm such a newb topic to Reasons why Deceth Sucks page.

**Comment by Deceth** [comment]
Your newsfeed on the github.com homepage should show a list of everything that's new with any project you are watching. A message pops up in my newsfeed whenever someone changes a wiki page or adds an issue.

**Comment by Rushing** [comment]
You learn something new every day.

**Comment by Deceth** [comment]
There is also a new Wiki History page available now! This lets you see any changes made on the entire wiki.
