### ISSUE TITLE
Don't hard-code server IP address in client! 

### ISSUE THREAD

**Issue by Deceth** [Deceth/Battle-City#35]
Right now the IP address for the server is hard-coded. This needs to be changed. Users should be able to change the IP address to point to any server of their choice.

**Comment by rileyw** [comment]
Should the login dialog be expanded to accept an IP address?
![Screen Shot 2013-04-02 at 12 23 25 PM](https://f.cloud.github.com/assets/23965/329675/3a27ff5a-9bba-11e2-9a9c-4d8a93b2146b.png)
![Screen Shot 2013-04-02 at 12 24 41 PM](https://f.cloud.github.com/assets/23965/329676/3a3700d6-9bba-11e2-843d-75667f23e620.png)

**Comment by Deceth** [comment]
Yes, that would be a perfect way to do things for now, especially if an IP address can still be set by default by whomever is distributing the game. First time players who download the game will just want it to work when they open it. But eventually, players will want a way to host their own server or login to their friends server.

Ideally there can eventually be a metaserver of sorts where players can select a server to join from a list of active servers, but that's overkill at the moment :)

**Comment by rileyw** [comment]
The [metaserver](http://en.wikipedia.org/wiki/Metaserver) route may have the highest value for players to find a game server with players, low latency, map rotation, and/or running a certain modification. I will attempt to build a version that adds an ip address text box and passes the value to the Winsock object.

**Comment by rileyw** [comment]
Looking at the game logic the ip address will need to be set before this dialog box; therefore, I am going to rearrange the game logic to open a connection window to capture from the user the appropriate ip address / hostname and port for the game server. These options will be saved to options.ini.

**Comment by rileyw** [comment]
Been working on documenting the game logic #48

**Comment by rileyw** [comment]
Should we store the last used game server address in options.ini?

**Comment by Deceth** [comment]
Yes, when a user loads Battle City, the game should remember the last server used. 

The default value for a player loading Battle City for the first time should be = deceth.no-ip.org (this server is not currently online, but it's online more often than any other server... so that's the logic)

If the server is offline, an error message should pop-up indicating: "Server currently offline. Please visit battlecity.org to find a list of active servers".

The goal here being, if the default server is down, players will visit battlecity.org and ask for/find an IP address to an active server. If there are no active servers, it could still start a discussion that ends with someone hosting a server which is a good thing.

Ideally, the IP address input can be a drop-down-list.

Then, if the user changes the default IP address, Battle City could keep a history of the last IP addresses used in the drop-down-list. That way, it would be possible for players to easily re-try connecting to several known servers before giving up.

---

One day in the future, another project would be to build a light-weight lobby server. This would be a chat-room / metaserver. Battle City servers would connect to the lobby and the lobby would then always have a list of active servers. This is a much bigger under-taking, so I'm only writing this here as a side-note.

##

**Comment by rileyw** [comment]
Thank you for the clarification. I have the following notes from your response.
- Battle City creates **options.ini** upon initial launch for loading options
- Battle City will use a new variable in **options.ini** for storing the current game server address
  - Default address will be _deceth.no-ip.org_
- Battle City will display a message box upon failing to connect to the current game server address
  - Message box text will be "Server currently offline. Please visit battlecity.org to find a list of active servers." 

> **New Business Rule** Players should visit battlecity.org to find the current active game server. If they are unable to find an active game server, the player should start a conversation in the community that should result in someone hosting a game server.
- Battle City will manage a history of game server addresses in **history.ini**
- Battle City will display the game server address history through a drop-down list

**Comment by Deceth** [comment]
Dude, you're awesome! You unraveled my spaghetti ramblings eloquently! :+1:

**Comment by rileyw** [comment]
A file named "gameServerHistory.log" will be generated to store game server addresses. This is delimited by newline. Need to update the message box text for failing to connect to a game server. @Deceth Should there be a Disconnect button on the Login screen that allows someone to return to the Connection Manager?
