### ISSUE TITLE
Battle City on Wikipedia

### ISSUE THREAD

**Issue by Deceth** [Deceth/Battle-City#44]
Battle City was once again deleted from Wikipedia. Need to create a good article with references and screenshots at:http://en.wikipedia.org/wiki/Battle_City_%28online_game%29

Then need to add link back to the list of open source video games: http://en.wikipedia.org/w/index.php?title=List_of_open-source_video_games&oldid=372533726

**Comment by Deceth** [comment]
I did a basic article as per above. Not sure how long it will last this time! 

The best way to keep an article alive on Wikipedia is to find lots of sources. So, please try and find outside websites that mention Battle City!

**Comment by Rushing** [comment]
It appears the reason for delete is because there isn't enough coverage. Kind of ironic that we hope to attain such coverage through the use of Wikipedia!

**Comment by Deceth** [comment]
Wikpedia is an encyclopedia. An encyclopedia must deny our existence if there is no proof!

I created a basic article, but did not have time to go back and add references and links to back-it up. No proof, so article deleted.

Better luck next time. ;)

**Comment by Rushing** [comment]
I don't know why, but I feel that I owe Battlecity big time, I spent a vast amount of time on it, and that time was probably some of the most fun I've ever had. As such, I must repay this glorious game. I'll find some time to make this Wikipedia article myself, if you wouldn't be too bothered by me doing it.

**Comment by Deceth** [comment]
I would not be bothered at all. That is the beauty of Wikipedia - collaboration.

**Comment by rileyw** [comment]
Wrote http://en.wikipedia.org/wiki/Battle_City_(open_source_game) real quick. Please edit as needed. We'll see how long it remains.

**Comment by Deceth** [comment]
Hey riley, that's really awesome thanks! I hope it sticks this time, you've got a lot of sources highlighted so that should help!

**Comment by rileyw** [comment]
Looks like our article has survived a week. Issue closed?

**Comment by Deceth** [comment]
I'll close it since it's fixed for now! The article looks good so hopefully someone doesn't decide to throw it into "consideration for deletion" again. The issue always seems to come down to attribution, so hopefully Wikipedia admins stay happy with the current list of supporting links.
