### ISSUE TITLE
Reduce Total Number of Med-kits

### ISSUE THREAD

**Issue by Deceth** [Deceth/Battle-City#5]
Rushing said: "We now have 5 med kits, I know this is so to make it more newbie friendly again, but I severely dislike it. Currently we have few people on, so we often have the issue of 1v1's, meaning the newbie takes 3 meds, and the pro takes 5 meds. He just tanks the whole battle, making it unfair for the newbie."

**Comment by Deceth** [comment]
The idea of 5 meds is again, keep people alive. Prolong duels, prolong battles. Yes, its harder to kill people, but you spend more time in the action part of the game and less time in the rebuilding phase or the re-spawning phase. That's what people wanted. It's still what people want, its just frustrating now because there aren't enough players.

**Comment by Rushing** [comment]
New players generally die before they even notice they have low health, meaning they don't even use med kits. They are soley abused by oldbies.

**Comment by Deceth** [comment]
Yes, all new players will suck at first. The extra-med has nothing to do with new players.

The extra med is to make sure that when I fight against you, we might get to battle for 3-4 minutes before one of us dies, instead of one of us dying in 30 seconds. 

30 second battles are boring. I want to attack a city and not instantly kill the defender. I want to have to work for it, outsmart him, duel a little.
