### ISSUE TITLE
Requesting new SFML branch

### ISSUE THREAD

**Issue by rileyw** [Deceth/Battle-City#71]
I have set up a branch in my forked repository named "SFML" that I'm using to refactor Battle City to use SFML. Upon creation of this branch I can submit pull requests to this branch. As it stands, I can only submit pull requests against existing branches.

**Comment by Deceth** [comment]
Hey Riley, sorry for taking so long! SFML branch now created!

**Comment by rileyw** [comment]
Awesome -- I have been working through SFML to become familiar with its API and working through game methodologies.
