### ISSUE TITLE
Cannot build on area where a player died

### ISSUE THREAD

**Issue by Rushing** [Deceth/Battle-City#8]
You cannot build an area where a player died.
Simple fix in CCollision.cpp,
// For each possible player,
    for (int a = 0; a < MAX_PLAYERS; a++) {
        if (p->Player[a]->X-48 <= X_48 && p->Player[a]->X+48 >= (X-2)_48 && p->Player[a]->Y-48 <= Y_48 && p->Player[a]->Y+48 >= (Y-2)_48 && (p->Player[a]->isDead == false)) {
            return 1;
        }

**Comment by Deceth** [comment]
Is this a bug, or the benefit of death? When all signs point to death, your sacrifice, if well placed, could greatly assist your fellow team mates in their quest for conquest...

**Comment by Rushing** [comment]
When you put it that way, I suppose so, but since players don't really see it like that, and attackers generally try and spread out to cause more of an issue for the mayor, well then I think it's more of a bug.

**Comment by Deceth** [comment]
At one point we tried to create an image of a 'dead' or 'blow-up' tank to display until you re-spawn.
